### ISSUE TITLE
library method removed from loader.php in OC 2.1.0.1

### ISSUE THREAD

**Issue by sarath-c-sandwich** [vanderson139/opencart-twig#3]
Something wrong with OC 2.1.0.1 library($library) method is already removed from load.php by default, then I added this method into the class. Your code is awesome. Thanks

> ```
> public function library($library) {
>     $file = DIR_SYSTEM . 'library/' . str_replace('../', '', (string)$library) . '.php';
> 
>     if (file_exists($file)) {
>         include_once($file);
>     } else {
>         trigger_error('Error: Could not load library ' . $file . '!');
>         exit();
>     }
> }
> ```

**Comment by vanderson139** [comment]
Thank you! I removed this method from the ocmod to avoid this issue.

before:

``` php
$this->library('twig');
```

after:

``` php
if(!class_exists('Twig_Environment')) {
    require_once(DIR_SYSTEM . 'library' . DIRECTORY_SEPARATOR . 'twig.php');
}
```
