### ISSUE TITLE
Support opencart 1.5.6?

### ISSUE THREAD

**Issue by saosangmo** [vanderson139/opencart-twig#4]
Could you support opencart 1.5.6 please.

**Comment by IP-CAM** [comment]
Opencart 1.5.6.x does NOT use TWIG Files

**Comment by saosangmo** [comment]
> Opencart 1.5.6.x does NOT use TWIG Files
2.x version had not support Twig yet. This package help us use Twig for old Opencart. Could you support me hack this for 1.5.6 version?
